#!/usr/bin/env node

var args = process.argv.slice(2);

if (args.length === 0) {
	// No command line arguments specified.
	console.error("Usage: tenkai-client-node [phone ip] [filename]");
	process.exit(-1);
}

var TenkaiClient = require("./tenkai-client");
var client = new TenkaiClient(args[0]);

client.connect(function() {
	client.identify();
	client.send(args[1], function() {
		client.leave();
	});
});
